version: '3.3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  
  web:
    build: .
    command: bundle exec rails s -p 8888 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:8888"
    depends_on:
      - postgres

volumes:
  postgres:
